# 编译 自定义 nginx 扩展 环境镜像
FROM nginx:1.25.3

# pcre FTP 源已经关闭，不再提供。
# wget https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz && \
    # tar -zxvf pcre-8.44.tar.gz && \
# 此镜像源采用 DEB822 在 /etc/apt/sources.list.d/debian.sources
# 修改镜像源文件 到 清华镜像
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/debian.sources && \
    apt -y update && \
    apt -y upgrade && \
    apt -y install gcc g++ make wget libpcre3-dev && \
    mkdir /wks && \
    cd /wks && \
    wget http://nginx.org/download/nginx-1.25.3.tar.gz && \
    tar -zxvf nginx-1.25.3.tar.gz && \
    wget https://www.zlib.net/zlib-1.3.tar.gz && \
    tar -zxvf zlib-1.3.tar.gz

WORKDIR /wks/nginx-1.25.3
